# Generated by Django 3.1.5 on 2021-07-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Upload File',
            },
        ),
    ]
