# Generated by Django 3.1.5 on 2021-07-09 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_time',
            field=models.TimeField(default=datetime.datetime(2021, 7, 9, 12, 18, 45, 619238, tzinfo=utc)),
        ),
    ]
