# Generated by Django 3.1.5 on 2021-07-09 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_auto_20210709_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_time',
            field=models.TimeField(default=datetime.time(17, 53, 25, 918006)),
        ),
    ]
